### ISSUE TITLE
Date filter is not working

### ISSUE THREAD

**Issue by JBComputech** [SPECUSA/SelfServiceBI#10]
Hi,
There is some issues with the Date filter, initially the not able to add the date filter, it was showing the error "The Date format should be YYYY-MM-DD". After debugging the code, I found that, the 
if (!e.filterScope.startDate.match(/^[0-9]{4}\-(0[1-9]|1[012])\-(0[1-9]|[12][0-9]|3[01])/)), no value was coming for e.filterScope.startDate, then I replaced the startDate with e.filterScope.filterValand then I was able to add the Date filter.

Then I more issue came like, when I select the calendar and click on submit button, then I saw the API which  is something like below

http://localhost:8083/pentaho/plugin/cda/api/doQuery?path=/home/Hospital.cda&dataAccessId=Admissions
&paramstartDate=2018-01-01,2018-03-09&paramendDate=2018-01-01,2018-03-09&outputIndexId=1

Here the startDate is taking both start and stop date.
similarly the endDate is taking both start and endDate.

Can you please help me how to resolve this issue.

**Comment by SPECUSA** [comment]
Hi ,

 

We are checking below one , Please specify the below versions.

1.       SSBI Version.

2.       Pentaho Version.

 

Regards, Pranav

**Comment by JBComputech** [comment]
Hi Pranav,
 Thanks for your response..
 The details you have asked for are as follows:

1.       SSBI Version.-- 2.0.1_p07_1_community
2.       Pentaho Version. -- 7.1.0.0.12

Please let me know if you need any more information on the same.

**Comment by JBComputech** [comment]
I tried the new version just updated few minutes ago and it also have the same issues exist.
 
Kindly help me to fix these issues please..

**Comment by SPECUSA** [comment]
Hi , 

 

We have pushed the new release , but still in review in progress by pentaho Team.

Once they approve then only it will be available for download. Otherwise it will be take old release.

 

Regards, Pranav

**Comment by JBComputech** [comment]
Thanks Pranav for the update..
I have just downloaded from git and tried.. ..
Can you please help me with the date issues in the older version please.

**Comment by JBComputech** [comment]
Hi Pranav,

 Can you please help me with the date issues on the version which I have shared with you on friday..
SSBI Version.-- 2.0.1_p07_1_community
Pentaho Version. -- 7.1.0.0.12

 This tool is coming really good, kindly help to fix the Date filter issue.

**Comment by SPECUSA** [comment]
Hi ,

 

Why you required the date issue resolved in older version.

Please take latest code from git , issue is already resolved in that one.

 

Regards, Pranav

**Comment by JBComputech** [comment]
Hi Pranav,

 I have tried with the new version, still the same issue is there.

Kindly help on this.

**Comment by JBComputech** [comment]
Hi Pravin,
I have followed the below steps with the new version.
1.Download the code from git
https://github.com/SPECUSA/SelfServiceBI/blob/master/SelfServiceBI-ce-2.0.2-p7_1.zip

2.unzip and put inside the pentaho system folder

C:\PentahoCE\pentaho-server-ce-7.1.0.0-12\pentaho-server\pentaho-solutions\system\SelfServiceBI

3.Restart the server

4.Create date filter with the selfservice, it shows the same error.

Is there any  steps I am missing, kindly help ..

**Comment by SPECUSA** [comment]
Hi @JBComputech 

We have committed new changes recently for version 2.0.2
Please take the new release from GIT

Regards,
SSBI team

**Comment by JBComputech** [comment]
Thank you.
I will take the new code from git and try it.
I will update you soon.
Thanks for the quick response..

**Comment by JBComputech** [comment]
Hi,
I have tried with the new version, now I am able to add the date filter without any issues.
But while passing the date filter to cda query, its not working. It pass both the dates to paramstartDate aswell as ParamendDate.

On click of Filter submit, the API shows like this

http://localhost:8083/pentaho/plugin/cda/api/doQuery?path=/home/Hospital.cda&dataAccessId=Admissions&
paramstartDate=2013-02-02,2018-02-28&paramendDate=2013-02-02,2018-02-28&outputIndexId=1

Please help me how to fix this.

I have attached the screenshots for your reference.

1.CDA Query
![cda](https://user-images.githubusercontent.com/37204223/37279417-c1daca46-2610-11e8-9677-c45b434be5bd.png)

2.SSBI
![ssbi](https://user-images.githubusercontent.com/37204223/37279428-cb234d08-2610-11e8-8752-2ba677e8178b.png)

Please suggest, if I am doing anything wrong.

**Comment by SPECUSA** [comment]
Hi @JBComputech 

You can now use one date parameter in CDA  and then parse the parameter value in SQL to use both start and end date

Hope this would help you. 

I'm closing the ticket as the actual issue has been resolved

**Comment by JBComputech** [comment]
Thanks..
