### ISSUE TITLE
On Filter Submit, shows Date format Error

### ISSUE THREAD

**Issue by JBComputech** [SPECUSA/SelfServiceBI#12]
Hi,
 After selecting the filter values and click on submit, it shows the error 
angular.min.js:117 TypeError: e[key].startDate.format is not a function.

Kindly help to fix this. 

-----------------------------------------------------------------------------------
(anonymous) @ angular.min.js:117
i.render @ Pinboard.min.js:1
resizeChart @ Pinboard.min.js:1
(anonymous) @ PinboardEditor.min.js:311
dispatch @ jquery-1.12.3.min.js:3
r.handle @ jquery-1.12.3.min.js:3
angular.min.js:117 TypeError: e[key].startDate.format is not a function
    at Object.parseParams (commonUtils.min.js:1)
    at Object.getQueryData (commonUtils.min.js:1)
    at i.render (Pinboard.min.js:1)
    at Object.resizeChart (Pinboard.min.js:1)
    at PinboardEditor.min.js:311
    at dispatch (jquery-1.12.3.min.js:3)
    at r.handle (jquery-1.12.3.min.js:3)

**Comment by JBComputech** [comment]
Hi,
Any update on this..

**Comment by SPECUSA** [comment]
Hi,

We are checking it.

Next version will be released soon

**Comment by JBComputech** [comment]
Thank you so much..

**Comment by SPECUSA** [comment]
Solved in new version 2.1.1.

**Comment by JBComputech** [comment]
Still having the same issue, When I select the date filter and submit, still it shows two dates in both start and enddate
http://localhost:8083/pentaho/plugin/cda/api/doQuery?path=/home/Sparsh/tset2.cda&dataAccessId=Lab&paramstartDate=%222018-01-01%22,%222018-04-16%22&paramendDate=%222018-01-01%22,%222018-04-16%22&outputIndexId=1

Implemented)
send @ jquery-1.12.3.min.js:4
ajax @ jquery-1.12.3.min.js:4
readJSONFile @ commonUtils.min.js:1
getQueryData @ commonUtils.min.js:1
i.render @ Pinboard.min.js:1
resizeChart @ Pinboard.min.js:1
(anonymous) @ Pinboard.min.js:1
dispatch @ jquery-1.12.3.min.js:3
r.handle @ jquery-1.12.3.min.js:3
angular.min.js:117 TypeError: Cannot read property 'length' of undefined
    at i.render (Pinboard.min.js:1)
    at Object.resizeChart (Pinboard.min.js:1)
    at Pinboard.min.js:1
    at dispatch (jquery-1.12.3.min.js:3)
    at r.handle (jquery-1.12.3.min.js:3)
(anonymous) @ angular.min.js:117
i.render @ Pinboard.min.js:1
resizeChart @ Pinboard.min.js:1
(anonymous) @ Pinboard.min.js:1
dispatch @ jquery-1.12.3.min.js:3
r.handle @ jquery-1.12.3.min.js:3
jquery-1.12.3.min.js:4 GET http://localhost:8083/pentaho/plugin/cda
